name: Automatic Deployment

on:
  push:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build target
        run: cargo build --release
      - name: Inspect
        run: cd ./target/release ls -la
