name: Automatic Deployment

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build target/release
        run: cargo build --release
      - name: Push the release
        run: |
          git checkout --orphan release
          git reset --hard
          cp ./target/release/quic-mpc ./quic-mpc
          git add quic-mpc
          git commit -m "ci: latest release"
          git push origin release --force
    env:
      CARGO_TERM_COLOR: always
      GIT_USER_NAME: github-actions[bot]
      GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
