name: Automatic Deployment

on:
  push:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build target/release
        run: cargo build --release
      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Push the release
        run: |
          git checkout --orphan release
          git reset --hard
          cp ./target/release/quic-mpc ./quic-mpc
          git add quic-mpc
          git commit -m "ci: latest release"
          git push origin release --force
