name: Automatic Deployment

on:
  push:
    branches: master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build target/release
        run: cargo build --release
      - name: Write scripts
        run: echo "./quic-mpc --port 8081 --seed bootstrap-1 --silent" > quic-mpc.sh
      - name: Push the release
        run: |
          git checkout --orphan release
          git reset --hard
          cp ./target/release/quic-mpc ./quic-mpc
          git add quic-mpc quic-mpc.sh
          git commit -m "ci: latest release"
          git push origin release --force
    env:
      CARGO_TERM_COLOR: always
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
